name: CI Testing
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: "Python ${{ matrix.python }} Django ${{ matrix.django }}"
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 8  # default is max available
      fail-fast: false
      matrix:
        include:
          # Django 3.2
          - django: "3.2"
            python: "3.8"
          # Django 4.2
          - django: "4.2"
            python: "3.10"
          - django: "5.0"
            python: "3.11"

    steps:
      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: |
          python -m pip install -U pip
          python -m pip install "Django~=${{ matrix.django }}" codecov -e .[tests]

      - name: Run Tests
        run: |
          echo "Python ${{ matrix.python }} / Django ${{ matrix.django }}"
          coverage run --rcfile=.coveragerc runtests.py
          codecov
        continue-on-error: ${{ contains(matrix.django, '5.1') }}
